name: Action Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
    # List files before checkout
      - name: List files
        run: |
          ls -a
          pwd
    # list files after checkout
      - name: checkout
        uses: actions/checkout@v1

      - name: list files after checkout
        run: |
          pwd
          ls -a

  
      - name: simple js Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
     #input
        with:
          who-to-greet: Jayshree
     # output     
      #- name: Log Greeting time
       # run: echo "${{ steps.greet.outputs.time }}"
