name: Repository Dispatch

on:
  push:
    branches: [ main ]
  #repository_dispatch:
    #types: my-Event
   # types: [ build, release]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Chain
        id: build-chain
        uses: ginxo/github-action-build-chain@v2.4
        with:
          definition-file: https://github.com/jassu2017/maven-simple/master/blob/.github/workflows/main.yml
        env:
          GITHUB_TOKEN: "${{ secrets.PASSPHRASE }}"
      
      #- name: checkout
       # uses: actions/checkout@v2
      #- name: Update the file content in other repository
       # run: |
        #  chmod +x scripts/list_content_repo.sh
         # ./scripts/list_content_repo.sh
        #with:
         # my_token: ${{ secrets.PASSPHRASE }}
        #env: 
         # my_token: ${{ secrets.PASSPHRASE }}
