name: parameterized shell script 

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter the name'
        required: true
        default: 'github-actions'

jobs:
    run-shell-script:
      runs-on: ubuntu-latest
      steps:
      - name: checkout 
        uses: actions/checkout@v2
      - name: Print the workspace
        run: echo ${{ github.workspace }}
      - name: run the script
        run: |
           chmod +x scripts/param-script.sh
           ./scripts/param-script.sh ${{ github.event.inputs.name }}

    
