name: parameterized shell script 

on: 
   schedule: 
      - cron: '6 * * * *'

      


jobs:
    run-shell-script:
      runs-on: ubuntu-latest
      steps:
      - name: checkout 
        uses: actions/checkout@v2
      - name: run the script
        run: |
           chmod +x scripts/param-script.sh
           param1='jayshree'
           ./scripts/param-script.sh "${param1}" 
