name: Repository Dispatch Triggered

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch Triggered
        if: github.event.action == 'event-demo'
        run: |
          echo "Workflow triggered successfully by repository dispatch action!"
      - name: checkout 
        uses: actions/checkout@v2
      #- name: run the script
       # if: github.event.action == 'event-demo'
       # run: |
        #   chmod +x scripts/param-script.sh
         #  ./scripts/param-script.sh ${{ github.event.inputs.name }}
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "jassu2017"
          git config user.email "jayshree.prasad@live.com"   
          
      - name: create directory if it is not present
        run: |
          if [ ! -e new_folder ] 
          then
            mkdir new_folder 
            git add .
            git commit -m "new_folder "
            git push origin main
          else
            echo "new_folder directory is already present."
          fi
          
    
          
      #- name: commit
       # run: |
          # Stage the file, commit and push
        #  git add .
         # git commit -m "new_folder "
          #git push origin main
            
          
          
