name: Repository Dispatch Triggered

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch Triggered
        if: github.event.action == 'event-demo'
        run: |
          echo "Workflow triggered successfully by repository dispatch action!"
          
      - name: checkout 
        uses: actions/checkout@v2
        with:
         ref: ${{ github.head_ref }}
      
      - name: run the script
        run: |
          echo "current dir"
          pwd
          echo "lists of files"
          ls -ltra
       
 
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "jassu2017"
          git config user.email "jayshree.prasad@live.com"   
          
      - name: create directory if it is not present
        run: |
          DIR="/home/runner/work/github-actions-test20/github-actions-test20"
          if [ -d "$DIR" ] 
           then
             ### Take action if $DIR exists ###
           echo "creating folder in  ${DIR}..."
           mkdir "new_folder"
          else
             ###  Control will jump here if $DIR does NOT exists ###
          echo "Error: ${DIR} not found. Can not continue."
          fi 
          
          echo "list files"
          ls -ltra
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .
          commit_message: added new_folder
          push_options: '--force'
          
      - name: checkout 
        uses: actions/checkout@v2
  
        
      - name: run the script
        run: |
          echo "current dir"
          pwd
          echo "lists of files"
          ls -ltra
      
            
          
          
