name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Print a string
        run: echo "Hi Github Actions - I am from main"
      - name: multiline scripts
        run: |
          node -v
          npm -v


